repos:
  - repo: local
    hooks:
      - id: Python generate home page
        name: Generate homepage
        entry: python3 ./create_index.py
        language: system
        always_run: true
        pass_filenames: false
